from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import io


def generate_report_pdf(prediction_row, reasons):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                             topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#0F766E")
    )
    heading_style = ParagraphStyle(
        "HeadingStyle", parent=styles["Heading2"], textColor=colors.HexColor("#0F766E")
    )

    elements = []
    elements.append(Paragraph("DiaCare AI – Health Report", title_style))
    elements.append(Spacer(1, 12))

    risk_label = "High Risk" if prediction_row["prediction"] == 1 else "Low Risk"
    risk_color = colors.HexColor("#DC2626") if prediction_row["prediction"] == 1 else colors.HexColor("#16A34A")

    info_data = [
        ["Name", prediction_row["patient_name"] or "-"],
        ["Date", prediction_row["created_at"]],
        ["Age", str(prediction_row["age"])],
        ["Gender", prediction_row["gender"]],
        ["BMI", str(prediction_row["bmi"])],
        ["Blood Glucose Level", f'{prediction_row["blood_glucose_level"]} mg/dL'],
        ["Prediction", risk_label],
        ["Confidence", f'{prediction_row["confidence"]}%'],
    ]

    table = Table(info_data, colWidths=[6*cm, 9*cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F0FDFA")),
        ("TEXTCOLOR", (1, 6), (1, 6), risk_color),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 20))

    elements.append(Paragraph("Why this prediction?", heading_style))
    elements.append(Spacer(1, 8))
    for reason in reasons:
        elements.append(Paragraph(f"• {reason}", styles["Normal"]))
        elements.append(Spacer(1, 4))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Recommendations", heading_style))
    elements.append(Spacer(1, 8))

    if prediction_row["prediction"] == 1:
        recs = [
            "Consult a doctor for a formal HbA1c / fasting glucose test.",
            "Reduce refined sugar and processed carbohydrate intake.",
            "Aim for at least 30 minutes of physical activity, 5 days a week.",
            "Monitor blood glucose levels regularly.",
        ]
    else:
        recs = [
            "Maintain your current healthy habits.",
            "Continue regular physical activity and balanced meals.",
            "Get periodic health check-ups to stay on track.",
        ]

    for rec in recs:
        elements.append(Paragraph(f"• {rec}", styles["Normal"]))
        elements.append(Spacer(1, 4))

    elements.append(Spacer(1, 24))
    elements.append(Paragraph(
        "<i>Disclaimer: This report is generated by an AI model for informational "
        "purposes only and is not a medical diagnosis. Please consult a licensed "
        "physician for medical advice.</i>",
        styles["Normal"]
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer
